<a href="https://colab.research.google.com/github/Md-Refat-Hosain/practice-ML-models/blob/main/Decision_Tree_(cdm).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Import all the libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sbn
import statistics as st

# Libraries For Text

import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

nltk.download('punkt')
nltk.download('stopwords')



from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import confusion_matrix
%matplotlib inline

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [ ]:
# Read the dataset

In [2]:
df = pd.read_csv('/content/04+-+decisiontreeAdultIncome.csv')

In [3]:
df

,age,wc,education,marital status,race,gender,hours per week,IncomeClass
0,38,Private,HS-grad,Divorced,White,Male,40,<=50K
1,28,Private,Bachelors,Married,Black,Female,40,<=50K
2,37,Private,Masters,Married,White,Female,40,<=50K
3,31,Private,Masters,Never-married,White,Female,50,>50K
4,42,Private,Bachelors,Married,White,Male,40,>50K
...,...,...,...,...,...,...,...,...
19782,53,Private,Masters,Married,White,Male,40,>50K
19783,22,Private,Some-college,Never-married,White,Male,40,<=50K
19784,40,Private,HS-grad,Married,White,Male,40,>50K
19785,58,Private,HS-grad,Widowed,White,Female,40,<=50K
19786,22,Private,HS-grad,Never-married,White,Male,20,<=50K

In [ ]:
# Check null values

In [4]:
df.isna().sum()

age               0
wc                0
education         0
marital status    0
race              0
gender            0
hours per week    0
IncomeClass       0
dtype: int64

In [ ]:
# Check data type

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19787 entries, 0 to 19786
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             19787 non-null  int64
 1   wc              19787 non-null  category
 2   education       19787 non-null  category
 3   marital status  19787 non-null  category
 4   race            19787 non-null  category
 5   gender          19787 non-null  category
 6   hours per week  19787 non-null  int64
 7   IncomeClass     19787 non-null  category
dtypes: category(6), int64(2)
memory usage: 426.4 KB

In [ ]:
# make 'object' data type to 'category'

In [10]:
df[['wc','education','marital status','race','gender','IncomeClass']] = df[['wc','education','marital status','race','gender','IncomeClass']].astype('category')

In [11]:
df

,age,wc,education,marital status,race,gender,hours per week,IncomeClass
0,38,Private,HS-grad,Divorced,White,Male,40,<=50K
1,28,Private,Bachelors,Married,Black,Female,40,<=50K
2,37,Private,Masters,Married,White,Female,40,<=50K
3,31,Private,Masters,Never-married,White,Female,50,>50K
4,42,Private,Bachelors,Married,White,Male,40,>50K
...,...,...,...,...,...,...,...,...
19782,53,Private,Masters,Married,White,Male,40,>50K
19783,22,Private,Some-college,Never-married,White,Male,40,<=50K
19784,40,Private,HS-grad,Married,White,Male,40,>50K
19785,58,Private,HS-grad,Widowed,White,Female,40,<=50K
19786,22,Private,HS-grad,Never-married,White,Male,20,<=50K

In [ ]:
# Create dummy variable here (it will give as 'bool' type)

In [13]:
dummy_df = pd.get_dummies(df, drop_first= True)

In [ ]:
# Change bool type to int

In [19]:
dummy_df= dummy_df.astype(int)

In [ ]:
# separate data to x and y

In [21]:
X = dummy_df.iloc[:,:-1]
y = dummy_df.iloc[:,-1]

In [ ]:
# split the data

In [26]:
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size= .3 , random_state= 42 , stratify= y)

In [ ]:
# Import DC classifier

In [25]:
from sklearn.tree import DecisionTreeClassifier

In [27]:
dtc = DecisionTreeClassifier(random_state=42)
dtc.fit(X_train , y_train)

y_preds = dtc.predict(X_test)

In [ ]:
# evaluate the model (score is: ~0.79 which is very good(closer or equal to 1 is better))

In [28]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test , y_preds)
score = dtc.score(X_test , y_test)

In [29]:
cm, score

(array([[3825,  548],
        [ 727,  837]]),
 0.7852450732693279)